[book]
authors = ["Léo DURET <leoduret@outlook.com>"]
language = "fr"
multilingual = false
src = "src"
title = "Projet CMI L3 - A Quick Marker Maker (aqmm)"

[output.html]
mathjax-support = true
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/hyyking/aqmm"
git-repository-icon = "fa-github"
site-url = "hyyking.github.com/aqmm"
